### PR TITLE
Keep websocket connection alive

### PR DESCRIPTION
**Pull request by canhlinh**
Whenever I try to put BTP running for a long time, it turns out this error:
```
btpsimple_src_1 | D|15:12:02.949106|19E7|-|icon|client.go:379 wsReadJSONLoop c.conns[192.168.128.3:55966] ReadJSON err:unexpected EOF
```

I believe this problem arose while I was working on my shaky network. To solve this problem, I'd like to add a keepalive function to the icon client.

P/S: After I added this function. BTP is working continuously 24 hours still now.

### CODE REVIEW

**Comment by jorisvial** [comment]
I tested the websocket using [this script](https://gist.githubusercontent.com/canhlinh/ea878d6dd72ca0870a9b0cbd3bb49c58/raw/cf13ede223d09cbf7b837f9c852ccb1fd2c92ff7/btp_websccket.go) and I also got disconnected after a while (15 minutes). So it's not just your network. But I agree it should not be expected for the network to be stable 14/7 so this feature is a must.

**Comment by jspark-icon** [comment]
Keep-alive (Ping/Pong) could not solve the problem of temporary disconnection or network disaster. it's for preventing disconnection on idle status of tcp-keepalive not allowed network.

**Comment by canhlinh** [comment]
@jspark-icon  you are right. In my case, my network was not disconnected. It was running with lagging and high ping.

**Review by jorisvial — APPROVED** [review]

**Review by dhlee-icon — APPROVED** [review]
It seems that this can ease the problem of idle disconnection. after reflecting this, further problem of network could be fixed later on.

**Comment by jorisvial** [comment]
@canhlinh After reflecting about it again with the team, we think this fix is not appropriate. While it may somehow fix your issue for your specific situation, we don't think it actually solve network connectivity issues properly. Without having the technical explanation why this ping/pong messaging makes the websocket more stable, we should not consider it as a fix.

What we would like to see instead is a re-connection mechanism. This is a better approach because it allows relays to recover from many different possible and unidentified network failure scenario.

Does that sound okay with you?

**Review by jorisvial — CHANGES_REQUESTED** [review]
After reflecting a bit more with the team, we concluded that this fix is not appropriate. While it may fix your issue in your specific situation, without a technical explanation of why this make the connection last longer, we should not apply the fix.

In theory the relay should receive a block update every 2 seconds. This should be enough to keep the connection alive. If no blocks is received for a a long time, the connection should not terminate either.

Based on this reflexion, we think that it would be better to have a re-connection mechanism instead of "bruteforcing" the connection every 3 seconds.

It's impossible to predict the possible network failure scenario relays will face. So having this re-connection mechanism would both solve your issue, while covering many more cases that we did not yet face.

How does that sound to you?

**Comment by jorisvial** [comment]
> @jorisvial
> _In theory the relay should receive a block update every 2 seconds. This should be enough to keep the connection alive. If no blocks is received for a a long time, the connection should not terminate either._
> 
> When I was testing with a testnet like (edgeware or moonbase) the relay did not update block every 2 seconds as you think.
> The monitor function will block util this [channel](https://github.com/icon-project/btp/blob/master/cmd/btpsimple/chain/chain.go#L356) is free. It mean the [_relay function](https://github.com/icon-project/btp/blob/master/cmd/btpsimple/chain/chain.go#L113) is processed. In case, the _relay function takes a long time to process its workload. The monitor will sleep for a while.

Right. That's what I meant by `in theory`. This does not change the validity of our comment I believe, whether it's 2 seconds, 10 seconds or more, the connection is not supposed to terminate this way.

> The monitor will sleep for a while.

How long are we talking about here?

**Comment by canhlinh** [comment]
> How long are we talking about here? 
in my test, A few minutes ís possible.

**Comment by canhlinh** [comment]
>Based on this reflexion, we think that it would be better to have a re-connection mechanism instead of "bruteforcing" the connection every 3 seconds.

each 10 seconds not 3 seconds.
We can change [this ](https://github.com/icon-project/btp/blob/fa5b7aa7514f5d3316b28060c501401bbc93706b/cmd/btpsimple/module/icon/client.go#L42) to 60 seconds as it usually does.

I  often set it to 60 seconds when I working with a TCP socket in another project ( MYSQL ....)  With BTP I haven't tested with 60 seconds yet.


keepalive is not reconnecting. It is a different team. Please refer [this](https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html)

**Comment by jorisvial** [comment]
I close this PR for now until the problem is properly identified and solved. Thanks you for bringing up this issue and for providing one possible patch.

If we find out that your solution is the most appropriate, we can re-open a PR.

Until then, let's talk about it here https://github.com/icon-project/btp/discussions/63 🚀

**Comment by jorisvial** [comment]
We need to add throttling mechanism to BMC. But that's not directly related with the issue. Please see. https://github.com/icon-project/btp/discussions/63#discussioncomment-919183

We have denied the PR because it's not required behavior. After discussing it a bit more, adding this code will not harm the network. So, we will accept this patch.

**Pull request merged**
