### PR TITLE
feat: add scripts to support manual run

### PR DESCRIPTION
**Pull request by trmaphi**
Add 2 scripts to support BTP documents
- mb_bmc_get_linkStat.js
- mb_fund_bmr.js

### CODE REVIEW

**Comment by canhlinh** [comment]
After provisioning successfully, We cleaned node-modules. So please use eth cli instead.
Please refer to this example https://github.com/icon-project/btp/blob/icondao/docker-compose/goloop2moonbeam/scripts/transfer_dev.sh#L19

**Comment by quangtran8588** [comment]
I have two files: `getLinkStatus` and `addFundBMR`. As suggested, I can use `eth cli` in adding some funds to BMR. How can I get a link status from BMC using `etc cli`?

**Comment by canhlinh** [comment]
@quangtran8588 Please refer this [command](https://github.com/icon-project/btp/blob/230e1cc3ef608aec6e75533e54d19e1795a91e89/docker-compose/goloop2moonbeam/scripts/transfer_icx.sh#L45)

**Comment by canhlinh** [comment]
@trmaphi ANW, this request is only for testing purposes. It should be done by the end-user in some way. for sample, they can jump into the docker terminal then call what command they want.

**Comment by trmaphi** [comment]
@canhlinh please make any suggestion with @quangtran8588 context of https://github.com/quangtran8588/devportal/tree/wip/btp-document/btp-document. I made a PR on the behalf of him.

**Comment by canhlinh** [comment]
@quangtran8588 Could you describe what you want? so I can make a better suggestion.

**Comment by quangtran8588** [comment]
The BTP Document's purpose is to guide users on how to build BTP Network (ICON <-> Moonbeam) manually. The docker is a lazy option. Those scripts, that I gave, just save them some steps instead 
- Moonbeam's BMC configuration [[here](/wip/btp-document/btp-document/Smart-Contracts-Configuration.md#3-config-moonriver-bmc)]
- Adding fund to BMR [[here](/wip/btp-document/btp-document/Smart-Contracts-Configuration.md#3-config-moonriver-bmc)]

**Pull request merged**
