### PR TITLE
Refactor reuse codec.RLP from goloop

### PR DESCRIPTION
**Pull request by trmaphi**

### CODE REVIEW

**Review by mohamedelshami — APPROVED** [review]
Looks good to me, cleans some of the dependencies as well.

**Comment by trmaphi** [comment]
@jspark-icon Please help me to review and merge this. Thank you

**Comment by canhlinh** [comment]
@trmaphi  From my view `common` package is copied from `goloop.`  The author just did not want to import gloop as a library. Possibly, They were waiting for the office `goloop` SDK. Instead of importing `goloop`, you can consider copying the latest update from goloop into this project.

**Comment by canhlinh** [comment]
@trmaphi  From my view `common` package is copied from `goloop.`  The author just did not want to import gloop as a library. Possibly, They were waiting for the office `goloop` SDK. Instead of importing `goloop`, you can consider copying the latest update from goloop into this project.

**Comment by leeheonseung** [comment]
@trmaphi @canhlinh

@canhlinh point is right.
And the point of time on copying decided to update the latest fix only in case of critical bugs.

**Comment by mohamedelshami** [comment]
@canhlinh @ @leeheonseung 

I'm new to Golang, but as far as I can see go module dependencies allows pointing to specific commit hash. I don't see why we need to copy.

**Comment by mksong-icon** [comment]
@mohamedelshami
Package dependency means not just using the source, but also following the upstream. It's a little awkward that it uses an upstream source of GOLOOP. And also ICON2 in GOLOOP isn't so mature, so it can be changed dramatically for its own purpose. That's why we copy sources here.

GOLOOP is a somewhat big source to import for just encoding decoding library.

There are some other codes come from GOLOOP to be addressed at this point. Until we decide to refactor all of them, we want to sustain copied sources.

**Comment by mohamedelshami** [comment]
@mksong-icon thanks for clarifying.

I did consider the package size, I didn't think including a single package from GOLOOP will result in pulling the entire upstream. In this case, it's better to copy the module. Publishing the RLP from GOLOOP as a separate library is probably an option too if it can be decoupled from other GOLOOP packages.

**Comment by trmaphi** [comment]
Close this MR, as if we need any changes, source code should be copied directly from goloop repo

**Pull request closed without merging**
